//generated by mcute
//for concolic testing state machines

#include <crest.h>
#include <stdio.h>
//#include <iostream>

int main(void) {
int desiredLevel;
int temprature;
int HighTemps, DesiredLevel, Temprature;

int Warnings;

CREST_int(desiredLevel);
CREST_int(temprature);
CREST_int(HighTemps);

if (HighTemps<=9){
   	printf("----branch visited: HighTemps<=9----\n");
	if (desiredLevel>0){
		DesiredLevel=desiredLevel;
    Warnings+=desiredLevel;
		printf("----branch visited: desiredLevel>0----\n");
	}
	else{
		printf("----branch visited: !(desiredLevel>0)----\n");
	}
	if (temprature>0){
		printf("----branch visited: temprature>0----\n");
		Temprature=temprature;
		if (Temprature>=90){
			HighTemps++;
			printf("----branch visited: temprature>=90----\n");
		}
		else{
			HighTemps--;
			printf("----branch visited: !(temprature>=90)----\n");
		}
	}
	else{
			printf("----branch visited: !(temprature>0)----\n");
	}
}else{
   	printf("----branch visited: !(HighTemps<=9)----\n");
}
}//main
