//generated by mcute
//for concolic testing state machines

#include <crest.h>
#include <stdio.h>
//#include <iostream>

int main(void) {
  int desiredLevel;
  int temprature;
  int HighTemps;

  CREST_int(desiredLevel);
  CREST_int(temprature);
  //CREST_int(HighTemps);

  if (temprature>=60 && desiredLevel>=5){
    printf("----branch visited: temprature>=60 && desiredLevel>=5 ----\n");
    HighTemps = temprature-60;
  }
  else{
    printf("----branch visited: !(temprature>=60 && desiredLevel>=5)----\n");
  }
}//main
