//generated by mcute
//for concolic testing state machines

#include <crest.h>
#include <stdio.h>
//#include <iostream>

int main(void) {
  int color, tmp=0;

  CREST_int(color);
  // CREST_int(temprature);
  //CREST_int(HighTemps);

  if (color>=0 && color<5){
    printf("----branch visited: color>=0 && color<5 ----\n");
    tmp+=color;
  }
  else{
    printf("----branch visited: !(color>=0 && color<5)----\n");
  }
  if (tmp>=2){
    printf("----branch visited: tmp>=2----\n");
  }else
  {
    printf("----branch visited: !tmp>=2----\n");
  }
}//main
