//generated by mcute
//for concolic testing state machines

#include <crest.h>
#include <stdio.h>
//#include <iostream>

int main(void) {
  int HighTemps;

  if (HighTemps>=10){
    printf("----branch visited: HighTemps>=10!!!, %d degrees more than standart!!!----\n", HighTemps);
  }else{
    printf("----branch visited: !(HighTemps>=10)----\n");
  }
}//main
