//generated by mcute
//for concolic testing state machines

#include <crest.h>
#include <stdio.h>
//#include <iostream>

int main(void) {
  int amount, tmp=10;

  CREST_int(amount);
  // CREST_int(temprature);
  //CREST_int(HighTemps);

  if (amount>=0 && amount<5){
    printf("----branch visited: amount>=0 && amount<5 ----\n");
    tmp*=amount;
  }
  else{
    printf("----branch visited: !(amount>=0 && amount<5)----\n");
  }
  if (tmp>10 && tmp<50){
    printf("----branch visited: tmp>10 && tmp<50----\n");
  }else
  {
    printf("----branch visited: !tmp>10 && tmp<50----\n");
  }
}//main
