//generating data
//int imin = std::numeric_limits<int>::min(); // min int value
//int imax = std::numeric_limits<int>::max(); //max int value
//TODO: fix this to generate numbers between ranges uniforly using a c++ library
//int inp1 = rand() % imax + imin;
int inp1 = rand() % 300000 + (-200000);
int inp2 = rand() % 300000 + (-200000);
int inp3 = rand() % 300000 + (-200000);
int inp4 = rand() % 300000 + (-200000);
printf("\ninputs generated by the harness (in random inp gen): %d, %d, %d, %d\n",inp1,inp2,inp3,inp4 );
vector<value_t> inputs;
inputs.push_back(inp1);
inputs.push_back(inp2);
inputs.push_back(inp3);
inputs.push_back(inp4);

//saving to a file so the action code can restore them from there
fileutil::writeInputs("input", inputs);

//send message to the current transition
if (next_t == "t1") {
  data.setup(0, 0).send();
  log.log ("++++++Harness: msg 'setup' sent");
} else if (next_t == "t2") {
  data.start(0, 0, 0, 0).send();
  log.log ("++++++Harness: msg 'start' sent");
}
TransitionIterationsExecuted++;
TotalIterationsExecuted++;
